In [1]:
#Luke Kurta
import pandas as pd

#resturants
df_rests = pd.read_csv(
    "../Project/team_project_dataset/restaurants_santa_barbara.csv",
    sep=",",
    encoding="latin-1",
    header=None
)

df_rests.columns = df_rests.iloc[0]
df_rests = df_rests[1:]
df_rests.reset_index(drop=True)

#test
df_test = pd.read_csv(
    "../Project/team_project_dataset/test_reviews_santa_barbara.csv",
    sep=",",
    encoding="latin-1",
    header=None
)

df_test.columns = df_test.iloc[0]
df_test = df_test[1:]
df_test.reset_index(drop=True)

#train
df_train = pd.read_csv(
    "../Project/team_project_dataset/train_reviews_santa_barbara.csv",
    sep=",",
    encoding="latin-1",
    header=None
)

df_train.columns = df_train.iloc[0]
df_train = df_train[1:]
df_train.reset_index(drop=True)

,review_id,user_id,business_id,stars,datetime,text
0,ixa--i8zAivs8rD10tleZQ,-0EcgtUXe1rzrkmdih_tYg,VgAKmXE8B7J0I_O_R13UKQ,4.0,2018-07-03 03:24:32,I lived here before and not once that I came t...
1,MHj1HEPM5Bv7_UhoiwOSGA,-0EcgtUXe1rzrkmdih_tYg,YrNtBUOUOYwmRZ_UVwH8iQ,4.0,2018-07-04 15:47:17,Totally a great experienced. Been coming to S...
2,_sTp9AsEu60ORSqqb9juJg,-0EcgtUXe1rzrkmdih_tYg,Aes-0Q_guDeYewMapFs_vg,4.0,2018-07-06 05:38:42,"Great outdoor seating, the servers are attenti..."
3,2Tcu86xzIADtfuy5jeio9A,-0EcgtUXe1rzrkmdih_tYg,9ugpNKKhnYRa51qXoxUw_A,3.0,2018-07-06 05:49:49,Went for the first time. The lady in the fron...
4,J6X5I_LQnii7QeIW79gBVg,-0EcgtUXe1rzrkmdih_tYg,DOfiulOub9hVPBCtiDl9Fw,3.0,2018-07-06 06:05:15,"Pizza was great, servers are friendly and atte..."
...,...,...,...,...,...,...
41576,hJ6_1V1gLMuWMUfPeaGomA,zyt0joW7uNeQof5tthQAHg,JjmmSW_QQh2Db4fuIEMATA,4.0,2013-09-08 02:32:56,I never had such a good pizza so fast! We had ...
41577,wqUCvQf_bP_gQxrFRz94LA,zyt0joW7uNeQof5tthQAHg,Aes-0Q_guDeYewMapFs_vg,3.0,2013-09-09 03:56:41,We had lunch at the longboard grill. The food ...
41578,CufxkovWUbBqcj8avCai_g,zyt0joW7uNeQof5tthQAHg,0CHIbqSkGWBr2KMkIUocEA,4.0,2013-09-09 04:31:33,So first let me say that this restaurant is in...
41579,0yQfK9Ci7fbX850-LEyJbw,zyt0joW7uNeQof5tthQAHg,U2hkeMI-q4cS35QolJYN0A,2.0,2013-09-10 02:46:32,"So if this is, as other reviewers state, the b..."
41580,LUm2Zis67T26o9EtaIyq8A,zyt0joW7uNeQof5tthQAHg,CoZ2mpsMBP8HUG1ymKoZTg,4.0,2013-09-10 21:36:37,"Finally, a place in Santa Barbara I can really..."

In [2]:
num_restaurants = len(df_rests['business_id'].unique()) #number of rests
num_restaurants_in_data = len(pd.concat([df_train, df_test])['business_id'].unique()) #num of rests in review data
restaurants_in_data_list = pd.concat([df_train, df_test])['business_id'].unique() #list of rests in review data
#df_train_unique = df_train.drop_duplicates(subset="business_id")
#df_rests.merge(df_train_unique, on="business_id") --> gives df of the restaurants present in the train data

missing_reviews = (df_train["text"].isna().sum()) + (df_test["text"].isna().sum()) #check missing vals (none)
missing_ratings = (df_train["stars"].isna().sum()) + (df_test["stars"].isna().sum()) #check missing vals (none)
num_ratings_reviews = df_train.shape[0] + df_test.shape[0] #for all of this, it's nice to have the count for both train and test, just to analyze the dataset. of course, when we begin training, the only data that matters is the train data -- the test data is technically "unknown" during training and testing (we are trying to approximate the test data)
num_ratings_reviews_train = df_train.shape[0]

print(num_restaurants)
print(num_ratings_reviews_train)

767
41581

In [3]:
#restaurants by category -- lists of types of restaurants
asian_categories = ["asian","japanese","sushi","thai","chinese","indian","korean","ramen"]
asian_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(asian_categories), "business_id"].unique())
num_asian = len(asian_list)

niche_categories = ["argentine", "moroccan", "german", "latin american", "caribbean"]
niche_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(niche_categories), "business_id"].unique())
num_niche = len(niche_list)

mexican_categories = ["mexican", "tacos"]
mexican_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(mexican_categories), "business_id"].unique())
num_mexican = len(mexican_list)

italian_categories = ["italian", "pizza"]
italian_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(italian_categories), "business_id"].unique())
num_italian = len(italian_list)

american_categories = ["american", "cajun/creole", "barbeque", "burgers", "delis", "bagels", "soul food"]
american_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(american_categories), "business_id"].unique())
num_american = len(american_list)

nightlife_categories = ["beer", "nightlife", "bars", "pubs", "breweries", "sports"]
nightlife_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(nightlife_categories), "business_id"].unique())
num_nightlife = len(nightlife_list)

fastfood_categories = ["fast food", "deli"]
fastfood_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(fastfood_categories), "business_id"].unique())
num_fastfood = len(fastfood_list)

cafe_categories = ["cafes", "breakfast"]
cafe_list = (df_rests.explode("categories").loc[lambda x: x["categories"].str.lower().isin(cafe_categories), "business_id"].unique())
num_cafe = len(cafe_list)

In [4]:
#let's do a similar thing, but now using the attributes. this requires a good bit of preprocessing, since the attributes column is in dictionary form but is all in a string --> we need to turn it from a string into a dictionary type, and then we also need to make sure we fix the values (the quotations are all over the place)

import ast
def str_to_dict(s):
    try:
        return ast.literal_eval(s)
    except: #need this or else it won't run
        return {}
df_rests['attributes_dict'] = df_rests['attributes'].apply(str_to_dict)

def clean_values(d):
    return {k: (v.strip("'\"") if isinstance(v, str) else v) for k, v in d.items()}
df_rests['attributes_dict'] = df_rests['attributes_dict'].apply(clean_values)

In [5]:
#now that we have the attributes column all nice, we can filter

good_for_kids_df = df_rests[df_rests['attributes_dict'].apply( lambda d: d.get('GoodForKids') == 'True' and d.get('RestaurantsAttire') == 'casual' and d.get('Alcohol') == "u'none")]

easy_food_df = df_rests[df_rests['attributes_dict'].apply( lambda d: d.get('RestaurantsAttire') == 'casual' and d.get('RestaurantsTakeOut') == 'True' or d.get('RestaurantReservations') == 'False' and d.get('RestaurantsPriceRange2') == '1')]

In [10]:
easy_food_df

,business_id,name,address,city,state,postal_code,categories,latitude,longitude,attributes,attributes_dict
1,IDtLPgUrqorrpqSLdfMhZQ,Helena Avenue Bakery,"131 Anacapa St, Ste C",Santa Barbara,CA,93101,"food, restaurants, salad, coffee & tea, breakf...",34.4144445,-119.6906718,"{'RestaurantsTakeOut': 'True', 'NoiseLevel': ""...","{'RestaurantsTakeOut': 'True', 'NoiseLevel': '..."
2,SZU9c8V2GuREDN5KgyHFJw,Santa Barbara Shellfish Company,230 Stearns Wharf,Santa Barbara,CA,93101,"live/raw food, restaurants, seafood, beer bar,...",34.4087147,-119.6850187,"{'OutdoorSeating': 'True', 'RestaurantsAttire'...","{'OutdoorSeating': 'True', 'RestaurantsAttire'..."
3,ifjluUv4VASwmFqEp8cWlQ,Marty's Pizza,2733 De La Vina St,Santa Barbara,CA,93105,"pizza, restaurants",34.4362361,-119.7261474,"{'Alcohol': ""u'none'"", 'BusinessAcceptsCreditC...","{'Alcohol': 'u'none', 'BusinessAcceptsCreditCa..."
5,Hqz96v1ymucUKNzIWfEKXw,Subway,"1936 State St, Ste B",Santa Barbara,CA,93101,"restaurants, delis, sandwiches, fast food",34.430822,-119.714156,"{'Alcohol': ""u'none'"", 'Caters': 'True', 'Bike...","{'Alcohol': 'u'none', 'Caters': 'True', 'BikeP..."
10,N-CBZKO37y_WSUN7ZMNGkg,Taqueria El Pastorcito,4427 Hollister Ave,Santa Barbara,CA,93110,"restaurants, mexican",34.4397058,-119.7708382,"{'NoiseLevel': ""u'average'"", 'RestaurantsAttir...","{'NoiseLevel': 'u'average', 'RestaurantsAttire..."
...,...,...,...,...,...,...,...,...,...,...,...
743,vyNMRa4U9gnrCzqR707GZA,Back Door Deli,315 Camino Del Remedio,Santa Barbara,CA,93110,"delis, sandwiches, restaurants, breakfast & br...",34.4441584,-119.7806479,"{'GoodForMeal': ""{'dessert': False, 'latenight...","{'GoodForMeal': '{'dessert': False, 'latenight..."
744,q-1ICFSqs2MwDGfe5tX-SQ,Yellow Belly,2611 De La Vina St,Santa Barbara,CA,93105,"american (new), pizza, pubs, nightlife, bars, ...",34.4348537,-119.7247287,"{'Music': ""{'dj': False}"", 'NoiseLevel': ""'ave...","{'Music': '{'dj': False}', 'NoiseLevel': 'aver..."
749,-nwNPb3G-0L95igrhkvMtw,Panda Express,605 Paseo Nuevo,Santa Barbara,CA,93101,"restaurants, fast food, chinese",34.4187220772,-119.7001659,"{'RestaurantsGoodForGroups': 'True', 'Restaura...","{'RestaurantsGoodForGroups': 'True', 'Restaura..."
752,J52h9uXJgEKyIz0iq8S0Xw,Piano Gastrolounge,129 E Anapamu St,Santa Barbara,CA,93101,"bars, american (new), lounges, nightlife, rest...",34.425305,-119.702695,"{'OutdoorSeating': 'True', 'RestaurantsGoodFor...","{'OutdoorSeating': 'True', 'RestaurantsGoodFor..."
761,hDr_bt6MEwlGvGCCKzyzhg,Goleta Coffee Co and Loca Vivant Kitchen,177 S Turnpike Rd,Santa Barbara,CA,93111,"restaurants, coffee & tea, breakfast & brunch,...",34.437516711,-119.7909391846,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","{'RestaurantsPriceRange2': '1', 'BusinessParki..."

In [6]:
#dataframe containing review info about each restaurant -- one using train and test data, one using only train
merge1 = pd.concat([df_train, df_test]).merge(df_rests, how = 'left', on = 'business_id')

#review count for each
review_counts = merge1.groupby('business_id').count()
df_rests = df_rests.set_index('business_id')
df_rests['review_count'] = review_counts['review_id']
df_rests = df_rests.reset_index()
df_rests['review_count'] = df_rests['review_count'].fillna(0).astype(int)

In [7]:
#average rating for each rest

merge1['stars'] = pd.to_numeric(merge1['stars'])
rating_avgs = merge1.groupby('business_id')['stars'].agg('mean').reset_index()
df_rests['avg_rating'] = df_rests['business_id'].map(rating_avgs.set_index('business_id')['stars'])
df_rests = df_rests.reset_index()

In [8]:
#percentiles for ratings for each rest
rating_25th = merge1.groupby('business_id')['stars'].quantile(.25).reset_index()
rating_50th = merge1.groupby('business_id')['stars'].quantile(.50).reset_index()
rating_75th = merge1.groupby('business_id')['stars'].quantile(.75).reset_index()
df_rests['25th_percentile'] = df_rests['business_id'].map(rating_25th.set_index('business_id')['stars'])
df_rests['50th_percentile'] = df_rests['business_id'].map(rating_50th.set_index('business_id')['stars'])
df_rests['75th_percentile'] = df_rests['business_id'].map(rating_75th.set_index('business_id')['stars'])
df_rests = df_rests.reset_index()

In [9]:
df_rests

,level_0,index,business_id,name,address,city,state,postal_code,categories,latitude,longitude,attributes,attributes_dict,review_count,avg_rating,25th_percentile,50th_percentile,75th_percentile
0,0,0,IDtLPgUrqorrpqSLdfMhZQ,Helena Avenue Bakery,"131 Anacapa St, Ste C",Santa Barbara,CA,93101,"food, restaurants, salad, coffee & tea, breakf...",34.4144445,-119.6906718,"{'RestaurantsTakeOut': 'True', 'NoiseLevel': ""...","{'RestaurantsTakeOut': 'True', 'NoiseLevel': '...",111,4.108108,3.0,4.0,5.0
1,1,1,SZU9c8V2GuREDN5KgyHFJw,Santa Barbara Shellfish Company,230 Stearns Wharf,Santa Barbara,CA,93101,"live/raw food, restaurants, seafood, beer bar,...",34.4087147,-119.6850187,"{'OutdoorSeating': 'True', 'RestaurantsAttire'...","{'OutdoorSeating': 'True', 'RestaurantsAttire'...",359,4.114206,4.0,4.0,5.0
2,2,2,ifjluUv4VASwmFqEp8cWlQ,Marty's Pizza,2733 De La Vina St,Santa Barbara,CA,93105,"pizza, restaurants",34.4362361,-119.7261474,"{'Alcohol': ""u'none'"", 'BusinessAcceptsCreditC...","{'Alcohol': 'u'none', 'BusinessAcceptsCreditCa...",29,4.068966,4.0,4.0,5.0
3,3,3,UFpCraqzFBAhtZqmxmiWsA,Cat Therapy,"1213 State St, Ste L",Santa Barbara,CA,93101,"themed cafes, cafes, pets, arts & entertainmen...",34.4233018995,-119.7054707479,"{'WheelchairAccessible': 'True', 'WiFi': ""u'fr...","{'WheelchairAccessible': 'True', 'WiFi': 'u'fr...",29,4.620690,5.0,5.0,5.0
4,4,4,Hqz96v1ymucUKNzIWfEKXw,Subway,"1936 State St, Ste B",Santa Barbara,CA,93101,"restaurants, delis, sandwiches, fast food",34.430822,-119.714156,"{'Alcohol': ""u'none'"", 'Caters': 'True', 'Bike...","{'Alcohol': 'u'none', 'Caters': 'True', 'BikeP...",0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
762,762,762,Hlx8S2GLF7hMuIKx4sU-gg,Cesar's Place,712 N Milpas St,Santa Barbara,CA,93103,"mexican, restaurants, fish & chips",34.4285995,-119.6882227,"{'BYOBCorkage': ""'no'"", 'RestaurantsReservatio...","{'BYOBCorkage': 'no', 'RestaurantsReservations...",50,4.080000,4.0,4.0,5.0
763,763,763,bVaRZDHkWdsHuARGxxpREw,Sushi Bar 29,1134 Chapala St,Santa Barbara,CA,93101,"japanese, restaurants, noodles, sushi bars",34.422291,-119.705339,"{'WiFi': ""u'no'"", 'RestaurantsTableService': '...","{'WiFi': 'u'no', 'RestaurantsTableService': 'T...",30,4.433333,4.0,5.0,5.0
764,764,764,izSgTrqebu8bN8ONOCs6cQ,Oat Bakery,5 W Haley St,Santa Barbara,CA,93101,"bakeries, vegan, specialty food, food delivery...",34.4165478074,-119.6956258296,"{'Alcohol': ""u'none'"", 'HasTV': 'False', 'Bike...","{'Alcohol': 'u'none', 'HasTV': 'False', 'BikeP...",49,4.734694,5.0,5.0,5.0
765,765,765,TSwMwVq5GtQh5LW2t32uGA,Woody's Roundup Bar & Grill,"Earl Warren Showgrounds, 3400 Calle Real",Santa Barbara,CA,93105,"barbeque, bars, restaurants, nightlife",34.4308945309,-119.7356450558,"{'Caters': 'True', 'BusinessParking': ""{'garag...","{'Caters': 'True', 'BusinessParking': '{'garag...",0,NaN,NaN,NaN,NaN
766,766,766,uriD7RFuHhLJeDdKaf0nFA,Pizza Guru,3534 State St,Santa Barbara,CA,93105,"restaurants, pizza, food",34.4406893,-119.7396807,"{'NoiseLevel': ""u'average'"", 'RestaurantsGoodF...","{'NoiseLevel': 'u'average', 'RestaurantsGoodFo...",98,3.755102,3.0,4.0,5.0